# Generated by Django 3.2.10 on 2021-12-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Packet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_id", models.PositiveIntegerField()),
                ("payload", models.CharField(max_length=2000, null=True)),
                ("packet_index", models.PositiveIntegerField()),
                ("last_chunk", models.BooleanField(null=True)),
            ],
        ),
    ]
