# Generated by Django 3.2.10 on 2021-12-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ancillary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packet",
            name="payload",
            field=models.CharField(default="", max_length=20000),
            preserve_default=False,
        ),
    ]
